# install.packages(c("RTextTools","topicmodels"))
# install.packages(c("topicmodels"))
# install.packages("RMySQL")
# install.packages("caret")
library(RMySQL)
library(RTextTools)
library(topicmodels)
require(tm)
mydb = dbConnect(MySQL(), user='root', password='sajal', dbname='Disease_names', host='localhost', passwd='sajal')
rs = dbSendQuery(mydb,'set character set "utf8"')
rs = dbSendQuery(mydb, "SELECT distinct Article FROM `Corpus_English` LIMIT 0,100")
data = fetch(rs, n=-1)
# data=iconv(data, "utf8", "ASCII", sub="")
# data(NYTimes)
# data <- NYTimes[sample(1:3000,size=1000,replace=FALSE),]
matrix <- create_matrix(data$Article, language="english", removeNumbers=TRUE, stemWords=TRUE, weighting=weightTf)
k <- length(unique(data$Topic.Code))
lda <- LDA(matrix, 2)
terms(lda)
topics(lda)